server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      default:
        maxRetryAttempts: 3
        waitDuration: 1000
  ratelimiter:
    instances:
      default:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 3s 