server:
  port: 8761

spring:
  application:
    name: discovery-server
  jackson:
    serialization:
      indent_output: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 