spring:
  config:
    import: optional:configserver:http://config-server:8888
  datasource:
    url: jdbc:mysql://mysql:3306/sems_expenses?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: sems
    password: sems
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true 