server:
  port: 0

spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:mysql://localhost:3307/sems_reporting
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: false
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 6
        max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Service URLs
services:
  expense:
    url: http://expense-service 