global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'gateway-service:8080'
        - 'user-service:8080'
        - 'expense-service:8080'
        - 'document-service:8080'
        - 'notification-service:8080'
        - 'reporting-service:8080'
        - 'discovery-server:8761'
        - 'config-server:8888' 