spring:
  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          search-locations: file:./config-repo
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 